version: '3.4'

services:
  contourbuilderdocker:
    image: contourbuilderdocker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - C:/Users/bwilson/source/repos/LiDAR:/data
  